FROM ubuntu:16.04

WORKDIR /collector

RUN apt update && false; while [ $? -ne 0 ]; do \
    apt install \
    python3-dev \
    python3-pip \
    -y --no-install-recommends; done

add ./collector.tar.gz /collector/
RUN chmod +x collector.py

CMD ["./collector.py"]
